fail_fast: true

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  - repo: local
    hooks:
      - id: clippy
        name: Rust clippy
        language: rust
        pass_filenames: false
        entry: cargo clippy --all-targets --all-features -- -Dwarnings
      - id: rustfmt
        name: Rust formatting
        language: rust
        pass_filenames: false
        entry: cargo fmt --all
      - id: dapp
        name: dApp prettier
        additional_dependencies:
          - prettier
          - prettier-plugin-astro
        language: node
        pass_filenames: false
        entry: prettier --write dapp
      - id: website
        name: website prettier
        additional_dependencies:
          - prettier
          - "@stellar/prettier-config"
        language: node
        pass_filenames: false
        entry: prettier --write "website/{blog,docs,src/pages}/**/*.{md,mdx}"

      # our custom action
      - id: tansu
        name: Send hash to Soroban contract before push
        language: python
        additional_dependencies:
          - soroban
        entry: python pre-commit/soroban_versioning_pre_push.py
        pass_filenames: false
        always_run: true
        require_serial: true
        stages:
          - pre-push
